title: "SunShare Connect"
description: "Tri-Source Water Node | HomeNode | MSSC | Solar Water Resilience"
theme: jekyll-theme-minimal
logo: /assets/sunshare-logo.png  # optional if you'd like to add later
show_downloads: false
google_analytics: false
