name: One-time import from external repositories

on:
  workflow_dispatch: {}  # run manually from the Actions tab

permissions:
  contents: write  # needed to push back to this repo

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination repo (this repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: One-time import
        env:
          # If any source repos are PRIVATE, create a PAT with 'repo' scope,
          # add it as a secret in this repo named SOURCE_REPO_TOKEN,
          # and it will be used automatically. Public repos work without it.
          GH_READ_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          REPOS=(
            "justindbilyeu/SunShare-TriSource"
            "justindbilyeu/SunShare-Connect-Initiative-"
            "justindbilyeu/eMSSC2"
          )

          mkdir -p imports

          for repo in "${REPOS[@]}"; do
            safe="${repo//\//-}"                  # e.g., justindbilyeu-SunShare-TriSource
            tmp="$RUNNER_TEMP/tmp-$safe"
            url="https://github.com/$repo.git"

            echo "==> Cloning $repo (default branch, shallow)"
            if [[ -n "${GH_READ_TOKEN:-}" ]]; then
              git -c http.extraheader="Authorization: Bearer $GH_READ_TOKEN" clone --depth 1 "$url" "$tmp"
            else
              git clone --depth 1 "$url" "$tmp"
            fi

            # If repo uses Git LFS, fetch large files (safe to run even if not using LFS)
            if command -v git-lfs >/dev/null 2>&1; then
              git lfs install --local || true
              git -C "$tmp" lfs pull || true
            fi

            dest="imports/$safe"
            echo "==> Copying files to $dest/"
            rm -rf "$dest"
            mkdir -p "$dest"
            rm -rf "$tmp/.git"

            # Copy including dotfiles
            shopt -s dotglob
            cp -a "$tmp"/* "$dest"/ || true
            shopt -u dotglob

            rm -rf "$tmp"
          done

      - name: Commit & push (if any changes)
        shell: bash
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "One-time import: SunShare-TriSource, SunShare-Connect-Initiative-, eMSSC2"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi

      - name: Summary
        run: |
          {
            echo "## Imported repositories"
            echo "- justindbilyeu/SunShare-TriSource → \`imports/justindbilyeu-SunShare-TriSource/\`"
            echo "- justindbilyeu/SunShare-Connect-Initiative- → \`imports/justindbilyeu-SunShare-Connect-Initiative-/\`"
            echo "- justindbilyeu/eMSSC2 → \`imports/justindbilyeu-eMSSC2/\`"
            echo
            echo "_You can delete or disable this workflow after the import._"
          } >> "$GITHUB_STEP_SUMMARY"
